parameters:
- name: Name
  displayName: 'Build Name'
  type: string

- name: Target
  displayName: 'Host Operating System'
  type: string

jobs:
- job: build_${{ parameters.Name }}
  displayName: Build ${{ parameters.Name }}
  pool: 
    vmImage: ${{ parameters.Target }}
  steps:
    - checkout: self
      submodules: true
    - powershell: ./scripts/init.ps1 -TargetOS ${{ parameters.Name }}
      displayName: Init build machine
    - powershell: ./scripts/build.ps1
      displayName: Build
    - publish: $(System.DefaultWorkingDirectory)/out
      artifact: out_${{ parameters.Name }}
